In [1]:
import pandas as pd
import os

dfs = []

for filename in os.listdir():
    if filename.endswith(".csv"):
        df = pd.read_csv(filename)
        dfs.append(df)

In [81]:
#concat three files
data = pd.concat(dfs, ignore_index=True)

In [82]:
# shuffle data
data = data.sample(frac=1, random_state=42).reset_index(drop=True)

In [83]:
data.head()

,id,age_years,gravidity,parity,gestational_age_weeks,bmi_pre_pregnancy,systolic_bp_mmhg,diastolic_bp_mmhg,hemoglobin_gdl,anemia_status,fasting_glucose_mgdl,proteinuria,hiv_status,anc_visits,delivery_mode,primary_complication,pregnancy_outcome,risk_level
0,2309,22,1,0,41.9,27.8,103,67,12.7,none,123,0,0,3,vaginal,gestational_diabetes,live_birth,moderate
1,2405,26,4,2,31.1,28.1,113,74,10.8,mild,103,1,0,3,vaginal,gestational_diabetes,live_birth,moderate
2,3398,29,2,0,27.5,17.5,109,67,11.1,none,82,0,0,1,vaginal,none,live_birth,low
3,5059,37,7,6,21.3,22.7,119,68,13.4,none,77,0,0,3,caesarean,none,live_birth,moderate
4,2665,15,1,0,17.8,20.5,120,71,13.7,none,76,0,0,3,vaginal,none,live_birth,high

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     30000 non-null  int64
 1   age_years              30000 non-null  int64
 2   gravidity              30000 non-null  int64
 3   parity                 30000 non-null  int64
 4   gestational_age_weeks  30000 non-null  float64
 5   bmi_pre_pregnancy      30000 non-null  float64
 6   systolic_bp_mmhg       30000 non-null  int64
 7   diastolic_bp_mmhg      30000 non-null  int64
 8   hemoglobin_gdl         30000 non-null  float64
 9   anemia_status          30000 non-null  object
 10  fasting_glucose_mgdl   30000 non-null  int64
 11  proteinuria            30000 non-null  int64
 12  hiv_status             30000 non-null  int64
 13  anc_visits             30000 non-null  int64
 14  delivery_mode          30000 non-null  object
 15  primary_complication   30000 non-null  object
 16  pregnancy_outcome      30000 non-null  object
 17  risk_level             30000 non-null  object
dtypes: float64(3), int64(10), object(5)
memory usage: 4.1+ MB

In [85]:
data.isnull().sum()

id                       0
age_years                0
gravidity                0
parity                   0
gestational_age_weeks    0
bmi_pre_pregnancy        0
systolic_bp_mmhg         0
diastolic_bp_mmhg        0
hemoglobin_gdl           0
anemia_status            0
fasting_glucose_mgdl     0
proteinuria              0
hiv_status               0
anc_visits               0
delivery_mode            0
primary_complication     0
pregnancy_outcome        0
risk_level               0
dtype: int64

# there is no nulls

In [86]:
data.describe()

,id,age_years,gravidity,parity,gestational_age_weeks,bmi_pre_pregnancy,systolic_bp_mmhg,diastolic_bp_mmhg,hemoglobin_gdl,fasting_glucose_mgdl,proteinuria,hiv_status,anc_visits
count,30000.000000,30000.000000,30000.0000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,5000.500000,26.049533,3.1750,2.070533,27.357543,23.706320,116.223467,72.681967,10.329173,84.929933,0.407833,0.100967,3.896133
std,2886.799445,5.521126,2.2361,2.211498,7.227483,4.289351,15.924999,11.022450,2.033087,12.085618,0.930126,0.301290,2.241275
min,1.000000,15.000000,1.0000,0.000000,6.000000,14.000000,72.000000,45.000000,3.100000,49.000000,0.000000,0.000000,0.000000
25%,2500.750000,22.000000,1.0000,0.000000,22.300000,20.600000,106.000000,66.000000,8.800000,77.000000,0.000000,0.000000,2.000000
50%,5000.500000,26.000000,3.0000,1.000000,27.600000,23.600000,114.000000,71.000000,10.600000,83.000000,0.000000,0.000000,4.000000
75%,7500.250000,30.000000,4.0000,3.000000,32.700000,26.600000,122.000000,77.000000,11.900000,90.000000,0.000000,0.000000,5.000000
max,10000.000000,47.000000,16.0000,15.000000,42.000000,39.800000,208.000000,133.000000,15.800000,165.000000,4.000000,1.000000,15.000000

**EDA**

In [87]:
#libraries
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [90]:
!pip install ipython --upgrade

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ipython in c:\users\admin\appdata\roaming\python\python314\site-packages (9.7.0)
Collecting ipython
  Downloading ipython-9.12.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: colorama>=0.4.4 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from ipython) (5.14.3)
Requirement already satisfied: wcwidth in c:\users\admin\appdata\roaming\python\python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\admin\appdata\roaming\python\python314\site-packages (from jedi>=0.18.2->ipython) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from stack_data>=0.6.0->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from stack_data>=0.6.0->ipython) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\admin\appdata\roaming\python\python314\site-packages (from stack_data>=0.6.0->ipython) (0.2.3)
Downloading ipython-9.12.0-py3-none-any.whl (625 kB)
   ---------------------------------------- 0.0/625.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/625.7 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/625.7 kB ? eta -:--:--
   ---------------------------------------- 625.7/625.7 kB 1.9 MB/s  0:00:00
Installing collected packages: ipython
  Attempting uninstall: ipython
    Found existing installation: ipython 9.7.0
    Uninstalling ipython-9.7.0:
      Successfully uninstalled ipython-9.7.0
Successfully installed ipython-9.12.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [91]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"
# for risk model
fig = px.histogram(data, x='risk_level', color='risk_level', text_auto=True,
                   title='Risk Level Distribution')
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
#anemia with hemoglobin (for risk level model)
fig = px.histogram(data, x='hemoglobin_gdl', nbins=50, marginal="box",
                   title='Hemoglobin Distribution')
fig.add_vline(x=11, line_dash="dash", line_color="orange", annotation_text="Anemia <11 g/dL")
fig.add_vline(x=7, line_dash="dash", line_color="red", annotation_text="Severe <7 g/dL")
fig.show()

In [ ]:
#the target for diagnosis model
fig = px.histogram(data, x='primary_complication', color='primary_complication',
                   title='Primary Complication Distribution',
                   text_auto=True)
fig.show()

In [ ]:
# for diagnosis model
fig = px.scatter(data, x='systolic_bp_mmhg', y='diastolic_bp_mmhg', color='primary_complication',
                 title='Blood Pressure by Complication', hover_data=['age_years','bmi_pre_pregnancy'])
fig.add_hline(y=90, line_dash="dash", line_color="red")
fig.add_vline(x=140, line_dash="dash", line_color="red")
fig.show()

In [ ]:
# gestational_diabestes has strong relation with bmi
fig = px.scatter(data, x='bmi_pre_pregnancy', y='fasting_glucose_mgdl', color='primary_complication',
                 title='BMI vs Fasting Glucose', hover_data=['age_years'])
fig.add_hline(y=92, line_dash="dash", line_color="red", annotation_text="GDM threshold")
fig.show()

In [ ]:
import plotly.express as px

fig = px.scatter(
    df,
    x='fasting_glucose_mgdl',
    y='systolic_bp_mmhg',
    color='primary_complication',
    marginal_x='histogram',
    marginal_y='histogram',
    hover_data=['age_years', 'proteinuria', 'bmi_pre_pregnancy'],
    title='Interactive Diagnosis Clusters: Sugar vs Blood Pressure',
    labels={
        'fasting_glucose_mgdl': 'Fasting Glucose (mg/dL)',
        'systolic_bp_mmhg': 'Systolic BP (mmHg)',
        'primary_complication': 'Diagnosis'
    },
    template='plotly_white',
    color_discrete_sequence=px.colors.qualitative.Vivid
)

fig.add_hline(y=140, line_dash="dash", line_color="red", annotation_text="High BP Threshold")
fig.add_vline(x=92, line_dash="dash", line_color="green", annotation_text="High Sugar Threshold")


fig.update_layout(
    legend_title_text='Medical Diagnosis',
    title_x=0.5
)

fig.show()

In [ ]:
# proteinuria has strong relation with preeclampsia and (elcampsia (rare))
import plotly.express as px

fig = px.box(
    df,
    x='primary_complication',
    y='proteinuria',
    color='primary_complication',
    points="all",
    notched=True,
    title='Kidney Signature: Proteinuria Levels by Diagnosis',
    labels={
        'primary_complication': 'Medical Diagnosis',
        'proteinuria': 'Proteinuria Level (0 to 4+)'
    },
    category_orders={"primary_complication": ["none", "gestational_diabetes", "preeclampsia"]},

)
fig.update_layout(
    yaxis_title="Proteinuria Score",
    xaxis_title="Diagnosis Category",
    showlegend=False
)

fig.show()

In [ ]:
# gestational_diabetes has the greatest median (pre_pregnenct_bmi has strong relation with gestational_daibetes)
import plotly.express as px

fig = px.box(
    df,
    x='primary_complication',
    y='bmi_pre_pregnancy',
    color='primary_complication',
    points="outliers",
    notched=True,
    title='Risk Factor Analysis: Pre-Pregnancy BMI by Diagnosis',
    labels={
        'primary_complication': 'Diagnosis Group',
        'bmi_pre_pregnancy': 'Pre-Pregnancy BMI (kg/m²)'
    },
    color_discrete_map={
        'none': 'green',
        'gestational_diabetes': 'orange',
        'preeclampsia': 'red'
    },
    template='plotly_white'
)

fig.add_hline(y=25, line_dash="dot", line_color="blue", annotation_text="Overweight (>25)")
fig.add_hline(y=30, line_dash="dash", line_color="darkred", annotation_text="Obese (>30)")

fig.update_layout(
    yaxis_title="BMI (kg/m²)",
    xaxis_title="Diagnosis",
    showlegend=False
)

fig.show()

In [ ]:
#heat map
import plotly.figure_factory as ff
import pandas as pd
import numpy as np

# primary_complication encoding
df_corr = data.copy()
df_corr['target_encoded'] = df_corr['primary_complication'].map({
    'none': 0,
    'gestational_diabetes': 1,
    'preeclampsia': 2
})


numeric_cols = [
    'age_years', 'bmi_pre_pregnancy', 'systolic_bp_mmhg',
    'diastolic_bp_mmhg', 'fasting_glucose_mgdl', 'proteinuria',
    'gravidity',
    'parity',
    'gestational_age_weeks', 'target_encoded'
]
corr_matrix = df_corr[numeric_cols].corr().round(2)


fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=list(corr_matrix.columns),
    y=list(corr_matrix.index),
    annotation_text=corr_matrix.values,
    colorscale='Viridis',
    showscale=True
)

fig.update_layout(
    title='Feature Correlation Matrix: Finding the Key Drivers',
    xaxis_showgrid=False,
    yaxis_showgrid=False,
    template='plotly_white'
)

fig.show()

In [ ]:
#KDE plot
import plotly.express as px

fig = px.histogram(
    data,
    x='age_years',
    color='primary_complication',
    marginal='box',
    histnorm='probability density',
    nbins=50,
    opacity=0.5,
    barmode='overlay',
    title='Age Distribution Analysis by Diagnosis',
    labels={'age_years': 'Age (Years)', 'primary_complication': 'Diagnosis'},
    template='plotly_white'
)


fig.update_layout(
    yaxis_title="Density",
    legend_title_text='Medical Condition',
    bargap=0.05
)

fig.show()

# **Feature engineering**

In [92]:
df_model=data.copy()

In [93]:
print("original:", df_model.shape)

original: (30000, 18)

In [95]:
cols_to_drop = [
    'id',
    'gravidity',
    'parity',
    'gestational_age_weeks',
    'hemoglobin_gdl',
    'anemia_status',
    'hiv_status',
    'anc_visits',
    'delivery_mode',
    'pregnancy_outcome',
    'risk_level'
]

df_model = df_model.drop(columns=cols_to_drop, errors='ignore')

In [96]:
print("original:", df.shape)

original: (10000, 18)

In [98]:
# convert bmi into categories
import pandas as pd

bins = [0, 18.5, 24.9, 29.9, float('inf')]
labels = ['Underweight', 'Normal', 'Overweight', 'Obese']

# new column
df_model['bmi_category'] = pd.cut(df_model['bmi_pre_pregnancy'], bins=bins, labels=labels)

#encoding
df_model['bmi_category_encoded'] = df_model['bmi_category'].cat.codes

print(df_model[['bmi_pre_pregnancy', 'bmi_category', 'bmi_category_encoded']].head())

   bmi_pre_pregnancy bmi_category  bmi_category_encoded
0               27.8   Overweight                     2
1               28.1   Overweight                     2
2               17.5  Underweight                     0
3               22.7       Normal                     1
4               20.5       Normal                     1

In [99]:
# drop Useless bmi's columns
df_model = df_model.drop(['bmi_pre_pregnancy', 'bmi_category'], axis=1)

print(df_model.columns)

Index(['age_years', 'systolic_bp_mmhg', 'diastolic_bp_mmhg',
       'fasting_glucose_mgdl', 'proteinuria', 'primary_complication',
       'bmi_category_encoded'],
      dtype='object')

In [100]:
print("after bmi:", df_model.shape)

after bmi: (30000, 7)

In [101]:
# apply Mean Arterial Pressure (MAP) equation
# equation: (Systolic + 2*Diastolic) / 3
df_model['MAP'] = (df_model['systolic_bp_mmhg'] + 2 * df_model['diastolic_bp_mmhg']) / 3

# Rounding the results
df_model['MAP'] = df_model['MAP'].round(2)


print(df_model[['systolic_bp_mmhg', 'diastolic_bp_mmhg', 'MAP']].head())

   systolic_bp_mmhg  diastolic_bp_mmhg    MAP
0               103                 67  79.00
1               113                 74  87.00
2               109                 67  81.00
3               119                 68  85.00
4               120                 71  87.33

In [102]:
# drop Useless
df_model = df_model.drop(['systolic_bp_mmhg', 'diastolic_bp_mmhg'], axis=1)

print(df_model.columns)

Index(['age_years', 'fasting_glucose_mgdl', 'proteinuria',
       'primary_complication', 'bmi_category_encoded', 'MAP'],
      dtype='object')

In [103]:
# drop rare values
values_to_drop = ['hemorrhage', 'severe_anemia', 'eclampsia']

df_model = df_model[~df_model['primary_complication'].isin(values_to_drop)]

#print remaining values
print("Remaining values")
print(df_model['primary_complication'].value_counts())

#Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_model['target_encoded'] = le.fit_transform(df_model['primary_complication'])


mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(mapping)

Remaining values
primary_complication
none                    21109
gestational_diabetes     3098
preeclampsia             2338
Name: count, dtype: int64
{'gestational_diabetes': np.int64(0), 'none': np.int64(1), 'preeclampsia': np.int64(2)}

In [104]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE

# --------------------------
# 1️⃣ Prepare data

# Multi-label targets
df_model['gestational_diabetes'] = (df_model['primary_complication'] == 'gestational_diabetes').astype(int)


# Features (remove target)
X = df_model[['age_years','fasting_glucose_mgdl','proteinuria','bmi_category_encoded','MAP']]
y_diabetes = df_model['gestational_diabetes']


# --------------------------
# 2️⃣ Preprocessing
numeric_features = ['age_years','fasting_glucose_mgdl','proteinuria','MAP']
categorical_features = ['bmi_category_encoded']

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numeric_features),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
])

# --------------------------
# 3️⃣ Train/test split
X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(X, y_diabetes, test_size=0.2, random_state=42, stratify=y_diabetes)

# --------------------------
# 4️⃣ Handle imbalance with SMOTE
smote = SMOTE(random_state=42)
X_train_d_res, y_train_d_res = smote.fit_resample(X_train_d, y_train_d)


# --------------------------
# 5️⃣ Define models
models = {
    'LogisticRegression': LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42),
    'RandomForest': RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss',
                             scale_pos_weight=(y_train_d==0).sum()/(y_train_d==1).sum(),
                             random_state=42)
}

# --------------------------
# 6️⃣ Function to train and evaluate
def train_eval(model, X_train, y_train, X_test, y_test, label, threshold=0.5):
    pipe = Pipeline([
        ('preprocess', preprocessor),
        ('model', model)
    ])
    pipe.fit(X_train, y_train)
    probs = pipe.predict_proba(X_test)[:,1]
    preds = (probs >= threshold).astype(int)

    print(f"===== {label} - {model.__class__.__name__} =====")
    print("Accuracy:", accuracy_score(y_test, preds))
    print("F1 Score:", f1_score(y_test, preds))
    print("Precision:", precision_score(y_test, preds))
    print("Recall:", recall_score(y_test, preds))
    print("ROC AUC:", roc_auc_score(y_test, probs))
    print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
    print("Classification Report:\n", classification_report(y_test, preds))
    print("\n")

    return pipe, probs

# --------------------------
# 7️⃣ Train and evaluate models for Gestational Diabetes
diabetes_pipes = {}
diabetes_probs = {}
threshold_diabetes = 0.7  # adjustable threshold to reduce False Positives

for name, model in models.items():
    pipe, probs = train_eval(model, X_train_d_res, y_train_d_res, X_test_d, y_test_d, "Gestational Diabetes", threshold=threshold_diabetes)
    diabetes_pipes[name] = pipe
    diabetes_probs[name] = probs

# --------------------------
# 9️⃣ Probabilities for the full dataset (optional)
diabetes_probs_full = diabetes_pipes['RandomForest'].predict_proba(X)[:,1]  # Example: using best model


results = pd.DataFrame({
    'diabetes_prob': diabetes_probs_full,

})

print(results.head())

===== Gestational Diabetes - LogisticRegression =====
Accuracy: 0.9352043699378414
F1 Score: 0.7370030581039755
Precision: 0.7005813953488372
Recall: 0.7774193548387097
ROC AUC: 0.9472017556532446
Confusion Matrix:
 [[4483  206]
 [ 138  482]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.96      0.96      4689
           1       0.70      0.78      0.74       620

    accuracy                           0.94      5309
   macro avg       0.84      0.87      0.85      5309
weighted avg       0.94      0.94      0.94      5309



===== Gestational Diabetes - RandomForestClassifier =====
Accuracy: 0.9320022603126766
F1 Score: 0.7114308553157475
Precision: 0.705229793977813
Recall: 0.717741935483871
ROC AUC: 0.9274938256317118
Confusion Matrix:
 [[4503  186]
 [ 175  445]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96      4689
           1       0.71      0.72      0.71       620

    accuracy                           0.93      5309
   macro avg       0.83      0.84      0.84      5309
weighted avg       0.93      0.93      0.93      5309

C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages\xgboost\training.py:200: UserWarning: [20:17:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

===== Gestational Diabetes - XGBClassifier =====
Accuracy: 0.8794499905820305
F1 Score: 0.6199524940617577
Precision: 0.4906015037593985
Recall: 0.8419354838709677
ROC AUC: 0.9331988387371956
Confusion Matrix:
 [[4147  542]
 [  98  522]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.88      0.93      4689
           1       0.49      0.84      0.62       620

    accuracy                           0.88      5309
   macro avg       0.73      0.86      0.77      5309
weighted avg       0.92      0.88      0.89      5309



   diabetes_prob
0          0.985
1          0.650
2          0.000
3          0.000
4          0.005

In [ ]:
# import pandas as pd
# from sklearn.model_selection import train_test_split, GridSearchCV
# from sklearn.preprocessing import StandardScaler, OneHotEncoder
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline
# from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix, classification_report
# from xgboost import XGBClassifier
# from imblearn.over_sampling import SMOTE
# import numpy as np

# # --------------------------
# # 1️⃣ Prepare data

# df_model['gestational_diabetes'] = (df_model['primary_complication'] == 'gestational_diabetes').astype(int)

# # Feature engineering
# df_model['glucose_bmi'] = df_model['fasting_glucose_mgdl'] * df_model['bmi_category_encoded']
# df_model['age_glucose'] = df_model['age_years'] * df_model['fasting_glucose_mgdl']

# X = df_model[['age_years','fasting_glucose_mgdl','proteinuria',
#               'bmi_category_encoded','MAP','glucose_bmi','age_glucose']]

# y = df_model['gestational_diabetes']

# # --------------------------
# # 2️⃣ Preprocessing

# numeric_features = ['age_years','fasting_glucose_mgdl','proteinuria','MAP','glucose_bmi','age_glucose']
# categorical_features = ['bmi_category_encoded']

# preprocessor = ColumnTransformer([
#     ('num', StandardScaler(), numeric_features),
#     ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
# ])

# # --------------------------
# # 3️⃣ Train test split

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y,
#     test_size=0.2,
#     stratify=y,
#     random_state=42
# )

# # --------------------------
# # 4️⃣ Handle imbalance

# smote = SMOTE(random_state=42)
# X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# # --------------------------
# # 5️⃣ Model

# xgb = XGBClassifier(
#     eval_metric='logloss',
#     scale_pos_weight=(y_train==0).sum()/(y_train==1).sum(),
#     random_state=42
# )

# pipe = Pipeline([
#     ('prep', preprocessor),
#     ('model', xgb)
# ])

# # --------------------------
# # 6️⃣ Hyperparameter tuning

# params = {
#     'model__n_estimators':[400,600],
#     'model__max_depth':[4,6,8],
#     'model__learning_rate':[0.03,0.05,0.1],
#     'model__subsample':[0.8,1],
#     'model__colsample_bytree':[0.8,1]
# }

# grid = GridSearchCV(
#     pipe,
#     params,
#     cv=5,
#     scoring='f1',
#     n_jobs=-1
# )

# grid.fit(X_train_res, y_train_res)

# best_model = grid.best_estimator_

# # --------------------------
# # 7️⃣ Predictions

# probs = best_model.predict_proba(X_test)[:,1]

# # اختيار threshold أفضل
# threshold = 0.55
# preds = (probs >= threshold).astype(int)

# # --------------------------
# # 8️⃣ Metrics

# print("Accuracy:", accuracy_score(y_test, preds))
# print("F1:", f1_score(y_test, preds))
# print("Precision:", precision_score(y_test, preds))
# print("Recall:", recall_score(y_test, preds))
# print("ROC AUC:", roc_auc_score(y_test, probs))

# print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
# print(classification_report(y_test, preds))

# # --------------------------
# # 9️⃣ Probabilities for full dataset

# diabetes_probs_full = best_model.predict_proba(X)[:,1]

# results = pd.DataFrame({
#     "diabetes_prob": diabetes_probs_full
# })

# print(results.head())

Accuracy: 0.9161800715765681
F1: 0.6894626657362177
Precision: 0.6076260762607626
Recall: 0.7967741935483871
ROC AUC: 0.9347737326206152
Confusion Matrix:
 [[4370  319]
 [ 126  494]]
              precision    recall  f1-score   support

           0       0.97      0.93      0.95      4689
           1       0.61      0.80      0.69       620

    accuracy                           0.92      5309
   macro avg       0.79      0.86      0.82      5309
weighted avg       0.93      0.92      0.92      5309

   diabetes_prob
0       0.999579
1       0.755642
2       0.109753
3       0.000022
4       0.000692

In [105]:
# --------------------------
# 🔟 Select final model (Logistic Regression)

final_model = diabetes_pipes['LogisticRegression']

# --------------------------
# 1️⃣1️⃣ Save the full pipeline (preprocessing + model)
import joblib

joblib.dump(final_model, "gestational_diabetes_logistic_pipeline.pkl")

print("✅ Model saved successfully!")

✅ Model saved successfully!

In [106]:
feature_names = X.columns.tolist()
joblib.dump(feature_names, "feature_names.pkl")

['feature_names.pkl']